# Generated by Django 4.1.1 on 2022-09-21 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(max_length=100)),
                ('revenue', models.CharField(max_length=100)),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HourlyPerformance',
            fields=[
                ('performance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.performance')),
                ('datetime', models.DateTimeField()),
            ],
            bases=('app.performance',),
        ),
    ]
